### ISSUE TITLE
Add CHANGELOG.md

### ISSUE THREAD

**Issue by luislobo** [arryon/sails-hook-fixtures#16]
It would be great to have a CHANGELOG.md file

**Comment by arryon** [comment]
Hi Luis, 

This repo is not very actively updated since for my purposes it's quite complete. However, on the next update (be it a PR, or something from myself) you can expect a changelog that also back-dates some old features. For now I'm closing this issue. Of course a PR adding a changelog is welcome, I'll review that as well.
